"""partition

Revision ID: ef81a3bec5d2
Revises: 3f2a9a7e14f1
Create Date: 2024-09-11 18:36:05.849831

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ef81a3bec5d2"
down_revision: str | None = "3f2a9a7e14f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE history RENAME TO history_2024")
    op.execute("""CREATE TABLE history(
                                    id uuid NOT NULL,
                                    user_id uuid NOT NULL,
                                    ip_address varchar(60) NOT NULL,
                                    action action NOT NULL,
                                    browser_info varchar(256),
                                    system_info varchar(256),
                                    created_at timestamp with time zone NOT NULL,
                                    FOREIGN KEY (user_id) REFERENCES "user"(id)
                                )
                                PARTITION BY RANGE (created_at)""")
    op.execute("ALTER TABLE history ATTACH PARTITION history_2024 FOR VALUES FROM (MINVALUE) TO ('2025-01-01')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("history")
    op.execute("alter table history_2024 rename to history")
    # ### end Alembic commands ###
