"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Optional
from opentelemetry.trace import Span

_Scope = Dict[str, Any]
_Message = Dict[str, Any]
ServerRequestHook = Optional[Callable[[Span, _Scope], None]]
ClientRequestHook = Optional[Callable[[Span, _Scope, _Message], None]]
ClientResponseHook = Optional[Callable[[Span, _Scope, _Message], None]]
