version: '3'
services:
  postgres:
    image: postgres:16
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 10s
  django:
    build: ./admin
    volumes:
      - ./admin/static:/opt/app/static
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./admin/static:/static:ro
      - ./data:/data:ro
    depends_on:
      - django
    ports:
      - "80:80"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200/_cat/health"]
      interval: 5s
      timeout: 10s

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    links:
      - elastic
    environment:
      ELASTICSEARCH_URL: http://elastic:9200

    ports:
      - 5601:5601

  redis:
    image: redis/redis-stack-server:latest
    volumes:
     - redisdata:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  etl:
    build: ./etl
    depends_on:
      postgres:
        condition: service_healthy
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy

  api:
    build: ./fastapi_api
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  esdata:
    driver: local
  redisdata:
    driver: local
