"""
This type stub file was generated by pyright.
"""

import abc
from typing import Optional, Sequence
from opentelemetry.exporter.jaeger.thrift.gen.jaeger import Collector as TCollector
from opentelemetry.sdk.trace import ReadableSpan, StatusCode
from opentelemetry.trace import SpanKind
from opentelemetry.util import types

OTLP_JAEGER_SPAN_KIND = ...
NAME_KEY = ...
VERSION_KEY = ...
_SCOPE_NAME_KEY = ...
_SCOPE_VERSION_KEY = ...
class Translator(abc.ABC):
    def __init__(self, max_tag_value_length: Optional[int] = ...) -> None:
        ...
    


class Translate:
    def __init__(self, spans) -> None:
        ...
    


class ThriftTranslator(Translator):
    ...


