"""
This type stub file was generated by pyright.
"""

from typing import Union
from opentelemetry.util.types import Attributes

class Observation:
    """A measurement observed in an asynchronous instrument

    Return/yield instances of this class from asynchronous instrument callbacks.

    Args:
        value: The float or int measured value
        attributes: The measurement's attributes
    """
    def __init__(self, value: Union[int, float], attributes: Attributes = ...) -> None:
        ...
    
    @property
    def value(self) -> Union[float, int]:
        ...
    
    @property
    def attributes(self) -> Attributes:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __repr__(self) -> str:
        ...
    


