version: '3'
services:
  redis-auth-dev:
    image: redis/redis-stack-server:latest
    volumes:
     - redis-auth-data-dev:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  postgres-auth-dev:
    image: postgres:16
    volumes:
     - postgres-auth-data-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./src/.env
    environment:
      POSTGRES_PASSWORD: "${AUTH_DB_PASSWORD}"
      POSTGRES_USER: "${AUTH_DB_USER}"
      POSTGRES_DB: "${AUTH_DB_NAME}"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 10s


volumes:
  redis-auth-data-dev:
    driver: local
  postgres-auth-data-dev:
    driver: local
