"""rename user_history.fingerprint -> user_history.fingreprint

Revision ID: 39e9d7c55c0a
Revises: a081387b15d1
Create Date: 2024-06-15 16:14:42.993510

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e9d7c55c0a'
down_revision: Union[str, None] = 'a081387b15d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('fingerprint', sa.String(length=255), nullable=False))
    op.drop_column('user_history', 'fingreprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('fingreprint', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('user_history', 'fingerprint')
    # ### end Alembic commands ###
