"""1

Revision ID: 4bc3aaff1409
Revises: cde0d3f57de8
Create Date: 2024-06-10 18:47:15.508837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc3aaff1409'
down_revision: Union[str, None] = 'cde0d3f57de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'user_history', ['id'])
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users_roles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_roles', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_superadmin')
    op.drop_constraint(None, 'user_history', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
