"""
This type stub file was generated by pyright.
"""

from .auth_jwt import AuthJWT as AuthJWT

"""Async fork of FastAPI extension that provides JWT Auth support (secure, easy to use and lightweight)"""
__version__ = ...
