"""
This type stub file was generated by pyright.
"""

from typing import Collection, Optional
from pkg_resources import Distribution

logger = ...
class DependencyConflict:
    required: str = ...
    found: Optional[str] = ...
    def __init__(self, required, found=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


def get_dist_dependency_conflicts(dist: Distribution) -> Optional[DependencyConflict]:
    ...

def get_dependency_conflicts(deps: Collection[str]) -> Optional[DependencyConflict]:
    ...

